import resend from "../config/resend.config.js";
import AppError from "../utils/app-error.js";

const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

const formatCurrency = (amount) => {
  return `₹${Number(amount || 0).toFixed(2)}`;
};

const getMonthName = (month) => {
  return monthNames[month - 1] || "Unknown Month";
};

const buildTopCategoriesHtml = (categories = []) => {
  if (!categories.length) {
    return "<li>No expense categories found for this month.</li>";
  }

  return categories
    .map(
      (category) =>
        `<li><strong>${category.category}</strong>: ${formatCurrency(
          category.amount
        )}</li>`
    )
    .join("");
};

const buildInsightsHtml = (insights = []) => {
  if (!insights.length) {
    return "<li>No AI insights available for this report.</li>";
  }

  return insights.map((insight) => `<li>${insight}</li>`).join("");
};

const buildMonthlyReportEmailHtml = (userName, report) => {
  const monthName = getMonthName(report.month);

  return `
    <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #222;">
      <h2>Hi ${userName || "there"},</h2>

      <p>Your FinSentry AI monthly finance report for <strong>${monthName} ${
    report.year
  }</strong> is ready.</p>

      <h3>Monthly Summary</h3>

      <table style="border-collapse: collapse; width: 100%; max-width: 600px;">
        <tr>
          <td style="border: 1px solid #ddd; padding: 8px;">Total Income</td>
          <td style="border: 1px solid #ddd; padding: 8px;"><strong>${formatCurrency(
            report.totalIncome
          )}</strong></td>
        </tr>
        <tr>
          <td style="border: 1px solid #ddd; padding: 8px;">Total Expense</td>
          <td style="border: 1px solid #ddd; padding: 8px;"><strong>${formatCurrency(
            report.totalExpense
          )}</strong></td>
        </tr>
        <tr>
          <td style="border: 1px solid #ddd; padding: 8px;">Balance / Savings</td>
          <td style="border: 1px solid #ddd; padding: 8px;"><strong>${formatCurrency(
            report.balance
          )}</strong></td>
        </tr>
        <tr>
          <td style="border: 1px solid #ddd; padding: 8px;">Transaction Count</td>
          <td style="border: 1px solid #ddd; padding: 8px;"><strong>${
            report.transactionCount
          }</strong></td>
        </tr>
      </table>

      <h3>Top Expense Categories</h3>
      <ul>
        ${buildTopCategoriesHtml(report.topExpenseCategories)}
      </ul>

      <h3>AI Summary</h3>
      <p>${report.aiSummary || "No AI summary available."}</p>

      <h3>AI Insights</h3>
      <ul>
        ${buildInsightsHtml(report.aiInsights)}
      </ul>

      <p style="margin-top: 24px;">
        Keep tracking your finances with FinSentry AI.
      </p>

      <p style="font-size: 12px; color: #666;">
        This is an automated monthly finance report generated by FinSentry AI.
      </p>
    </div>
  `;
};

const buildMonthlyReportEmailText = (userName, report) => {
  const monthName = getMonthName(report.month);

  const topCategoriesText = report.topExpenseCategories?.length
    ? report.topExpenseCategories
        .map(
          (category) =>
            `- ${category.category}: ${formatCurrency(category.amount)}`
        )
        .join("\n")
    : "- No expense categories found.";

  const insightsText = report.aiInsights?.length
    ? report.aiInsights.map((insight) => `- ${insight}`).join("\n")
    : "- No AI insights available.";

  return `
Hi ${userName || "there"},

Your FinSentry AI monthly finance report for ${monthName} ${
    report.year
  } is ready.

Monthly Summary:
Total Income: ${formatCurrency(report.totalIncome)}
Total Expense: ${formatCurrency(report.totalExpense)}
Balance / Savings: ${formatCurrency(report.balance)}
Transaction Count: ${report.transactionCount}

Top Expense Categories:
${topCategoriesText}

AI Summary:
${report.aiSummary || "No AI summary available."}

AI Insights:
${insightsText}

Keep tracking your finances with FinSentry AI.

This is an automated monthly finance report generated by FinSentry AI.
`;
};

export const sendMonthlyReportEmail = async ({ to, userName, report }) => {
  if (!to) {
    throw new AppError("Recipient email is required.", 400);
  }

  if (!report) {
    throw new AppError("Monthly report is required to send email.", 400);
  }

  const monthName = getMonthName(report.month);

  const subject = `Your FinSentry Monthly Report - ${monthName} ${report.year}`;

  const html = buildMonthlyReportEmailHtml(userName, report);
  const text = buildMonthlyReportEmailText(userName, report);

  const { data, error } = await resend.emails.send({
    from: process.env.RESEND_FROM_EMAIL || "FinSentry AI <onboarding@resend.dev>",
    to,
    subject,
    html,
    text,
  });

  if (error) {
    throw new AppError(
      error.message || "Failed to send monthly report email.",
      502
    );
  }

  return {
    emailId: data?.id,
    to,
    subject,
  };
};